version: '3.4'

networks:
  dashboard-network:
    driver: bridge

services:
  dashboard-nginx:
    container_name: dashboard-nginx
    image: nginx:stable-alpine
    ports:
      - "${DOCKER_NGINX_CLIENT_PORT:-26500}:8080"
      - "${DOCKER_NGINX_SERVER_PORT:-26501}:8081"
    networks:
      - dashboard-network
    volumes:
      - ./server/:/var/www/server
      - ./client/public:/var/www/client/public
      - ./client/src:/var/www/client/src
      - ./docker/etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - dashboard-php
      - dashboard-mysql

  dashboard-php:
    build:
      context: .
      dockerfile: docker/etc/php/main.Dockerfile
    container_name: dashboard-php
    ports:
      - "${DOCKER_PHP_PORT:-26502}:9000"
    networks:
      - dashboard-network
    depends_on:
      - dashboard-mysql
    volumes:
      - ./server/:/var/www/server

  dashboard-mysql:
    container_name: dashboard-mysql
    image: mysql:8.0
    networks:
      - dashboard-network
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DOCKER_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DOCKER_MYSQL_DB}
      MYSQL_USER: ${DOCKER_MYSQL_USER}
      MYSQL_PASSWORD: ${DOCKER_MYSQL_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "${DOCKER_MYSQL_PORT:-26503}:3306"

  dashboard-mysql-test:
    container_name: dashboard-mysql-test
    image: mysql:8.0
    networks:
      - dashboard-network
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DOCKER_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DOCKER_MYSQL_DB_TEST}
      MYSQL_USER: ${DOCKER_MYSQL_USER}
      MYSQL_PASSWORD: ${DOCKER_MYSQL_PASSWORD}
    ports:
      - "${DOCKER_MYSQL_TEST_PORT:-26504}:3306"

  dashboard-node:
    container_name: dashboard-node
    image: node:latest
    working_dir: /var/www/client
    networks:
      - dashboard-network
    volumes:
      - ./client/:/var/www/client
    command: sh -c "npm install && npm run watch"
volumes:
    mysql-data:
